auth0/resource_auth0_rule.go
auth0/resource_auth0_rule_config.go
auth0/resource_auth0_rule_config_test.go

With this PR we can cross Rules and Rules Config from yieldr/terraform-provider-auth0/issues/7

Rule / Rule Config read remote values correctly

---

auth0/resource_auth0_custom_domain.go
auth0/resource_auth0_custom_domain_test.go

Custom Domain read remote values correctly

---

auth0/resource_auth0_client_grant.go
auth0/resource_auth0_client_grant_test.go

read client grant from remote source correctly

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_custom_domain_test.go

This PR fixes #24 where name and strategy were being sent when an update was performed. We ignore them now and to update these properties a new resource needs to be created.

Changing name or strategy forces new resource

---

auth0/resource_auth0_client.go

The correct property in auth0 client is oidc_conformant,
but readClient method refers to oidc_compliant.
This commit fixes incorrect reference.

Fix oidc_conformant property

---

auth0/resource_auth0_rule.go
auth0/resource_auth0_rule_test.go

Current regexp for rule name does not allow spaces, but it should.
This commit fixes the issue.

Fix rule name regexp

---

Gopkg.lock
Gopkg.toml
auth0/provider.go
auth0/provider_test.go
vendor/github.com/yieldr/go-auth0/management/connection.go
vendor/github.com/yieldr/go-auth0/management/management.go

Cannot check if this actually works right now, because we need to have updated vendored **go-auth0** with this https://github.com/yieldr/go-auth0/pull/11.
So this is a WIP until vendors are updated.

Add debug property to provider

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
example/connection/main.tf

Fixes #40. Defined schema for `password_history` to properly support setting the `enable` and `size` fields.

Improve support for password history

---

auth0/resource_auth0_custom_domain.go

This fixes #55 where creating a custom domain would crash if it were already verified. Auth0 doesn't include a verification object if it has already been verified, causing this provider to crash.

Fix CustomDomain crash when already verified

---

auth0/resource_auth0_client.go
auth0/resource_auth0_client_test.go

When client_metadata is applied the provider panics with the following error:
`
panic: interface conversion: interface {} is map[string]interface {}, not []interface {}
2018-12-05T14:39:36.374+0700 [DEBUG] plugin.terraform-provider-auth0:
2018-12-05T14:39:36.374+0700 [DEBUG] plugin.terraform-provider-auth0: goroutine 211 [running]:
2018-12-05T14:39:36.374+0700 [DEBUG] plugin.terraform-provider-auth0: github.com/yieldr/terraform-provider-auth0/auth0.List(0x1b85480, 0xc0001ea230, 0x1a21df9, 0xf, 0xc00045ed80)
2018-12-05T14:39:36.374+0700 [DEBUG] plugin.terraform-provider-auth0:   /Users/anton.mednonogov/prj/go/src/github.com/yieldr/terraform-provider-auth0/auth0/resource_data.go:115 +0x146
`
I am a new person in Go, so if you have suggestions how to improve the PR, I'd be more than happy :)

Fix the error for managing client metadata

---

auth0/resource_auth0_rule_config.go

By spec, auth0 rule configuration variables are obfuscated to allow for secrets to be stored in them. This correspondingly marks the TF value as sensitive.

fix: mark rule-config value as sensitive

---

auth0/resource_auth0_email.go

Email provider credentials should be marked as sensitive to hide their output.

Mark keys as sensitive in auth0_email

---

README.md

Replace 'make install' by 'make build'. There is no 'install' target in the GNUMakefile

Fix compile instructions in the README

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go

Hello
When I create a Connection with enabled_clients, the order of the ids is not always the same.
I have an error like that:
```
testing.go:527: Step 0 error: After applying this step, the plan was not empty:
DIFF:
UPDATE: auth0_connection.my_connection
enabled_clients.0: "VciGGT5jZGbIlYC3nKABabKGjFlx8pMD" => "d8Io6XgKtoUHScGqmcniX9lLHpl4CHbE"
enabled_clients.1: "d8Io6XgKtoUHScGqmcniX9lLHpl4CHbE" => "xUolj4m6SejtAjtP3czFiSZw3f7M7c4q"
enabled_clients.2: "xUolj4m6SejtAjtP3czFiSZw3f7M7c4q" => "yqncnHsP3Gane086n5s70ucEUyuVFZ0Q"
enabled_clients.3: "yqncnHsP3Gane086n5s70ucEUyuVFZ0Q" => "VciGGT5jZGbIlYC3nKABabKGjFlx8pMD"
```
I propose to add a DiffSuppressFunc on the attribute.
But the verification is slow (up to 6s on my computer and auth0 tenant).
Do you think of another solution ?

the Connection's enabled_clients attribute is not indempotent

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go

* fix schema for connection option `password_no_personal_info` such that enabling/disabling personal data usage in passwords works as expected
```
$ make testacc TESTS=TestAccConnection
TF_ACC=1 go test $(go list ./...) -v  -timeout 120m -coverprofile="c.out" -run ^TestAccConnection$
? …
```

fix incorrect schema for connection option password_no_personal_info

---

auth0/resource_auth0_client.go

This PR implemented simple validation for the field `app_type` of resource `auth0_client`, this helps avoid sending extra API requests to (and receiving errors from) Auth0 management.
The validation and format follow the sample from [the validation of `auth0_connection`](https://github.com/alexkappa/terraform-provider-auth0/blame/master/auth0/resource_auth0_connection.go#L34) 
Please note that, unlike the `strategy` of `auth0_connection`, the field `app_type` of `auth0_client` is case-sensitive, when I tried `app_type = SPA` I got the following errors
```
Error: 400 Bad Request: Payload validation error: 'Invalid value "SPA"' on property app_type (The type of application this client represents).
```
* Please vote on this pull request by adding a 👍 …

Use StringInSlice to validate the app_type field for auth0_client

---

auth0/resource_auth0_connection.go
auth0/resource_data.go

The `schema.Set` type is intended for unordered lists, so using it means
we don't need to define a `DiffSuppressFunc` to prevent differences from
appearing due to the ordering of the enabled clients.
The `DiffSuppressFunc` was causing incorrect behaviour when adding a new
enabled client to a connection so rather than fix the function using a
set seems simpler.

Use set instead of list for enabled clients

---

example/tenant/main.tf

There currently is no example on how to use the tenant resource. However, there is one in PR https://github.com/alexkappa/terraform-provider-auth0/pull/90. But I dont think we should have to wait for the documentation to be completed for the tenant resource example to be available for everyone to view.

Add tenant example

---

auth0/resource_auth0_user.go

* Mark the password attribute as sensitive on the user resource.

mark password sensitive on user resource

---

README.md

Just an edit to make note of the 0.12.x support.

Call out support for Terraform 0.12.x in README Re: (#120)

---

auth0/resource_auth0_resource_server.go
auth0/resource_auth0_resource_server_test.go

* Add "enforce_policies" boolean attribute to ResourceServer
```
$ make testacc TESTS=TestAccResourceServer 
TF_ACC=1 go test $(go list ./...) -v  -timeout 120m -coverprofile="c.out" -run ^TestAccResourceServer
=== RUN   TestAccResourceServer
--- PASS: TestAccResourceServer (1.23s)
PASS
coverage: 15.0% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	1.248s	coverage: 15.0% of statements
```

add "enforce_policies" attribute to ResourceServer

---

auth0/resource_auth0_connection.go

Fixes #139
`
* Add the required code to the `buildConnection` function.
```
$ make testacc TESTS=TestSalesforceCommunityConnection
TF_ACC=1 go test $(go list ./...) -v  -timeout 120m -coverprofile="c.out" -run ^TestSalesforceCommunityConnection
? …
```

[FIX] Missing config in the buildConnection function

---

auth0/resource_auth0_email_template.go

According to the API docs, `body` is required, and `result_url` and `url_lifetime_in_seconds` are optional: https://auth0.com/docs/api/management/v2#!/Email_Templates/post_email_templates

Fixed optionality of email template fields

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_resource_server.go

* Add `password_complexity_options` to Auth0 `connection`
* Add `token_dialect` to Auth0 `resource_server`
Requires https://github.com/go-auth0/auth0/pull/69 to be merged in first

Add PasswordComplexityOptions to Connection and TokenDialect to Resource Server

---

auth0/resource_auth0_resource_server.go
auth0/resource_auth0_resource_server_test.go

Fixes #93 
* resource/auth0_resource_server: `signing_secret` is now also `Computed: true`. If set it's validated to be at least 16 characters.
```
$ make testacc TESTS=TestAccResourceServer
=== RUN …
```

Fix resource server signing secret

---

auth0/resource_auth0_resource_server.go

Fixes #86
* auth0_resource_server: update forces new resource.
```
$ make testacc TESTS=TestAccResourceServer                                  [13:31:11]
=== RUN   TestAccResourceServer
--- PASS: TestAccResourceServer …
```

Fix resource_server identifier to force new resource if updated

---

.github/workflows/labeler.yml
auth0/resource_auth0_user.go
auth0/resource_auth0_user_test.go

Fixes #119 
* Return `readUser()` after `createUser()` has run.
```
$ make testacc TESTS=TestAccUser                                   [18:43:12]
TF_ACC=1 go test $(go list ./...) -v  -timeout 120m -coverprofile="c.out" -run ^TestAccUser
?       github.com/alexkappa/terraform-provider-auth0 …
```

Fix update user

---

.github/labeler.yml
auth0/provider.go
auth0/resource_auth0_client.go
auth0/resource_auth0_client_test.go
auth0/resource_data.go

Fixes #96
* resource/auth0_client: fixes `is_first_party` setting if set to zero value.
* resource_data: checks for `IsNewResource() || HasChange()` instead of only `HasChange()`.
```
$ make testacc
...
PASS
coverage: 79.7% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	15.436s	coverage: 79.7% of statements
```

Fix client is_first_party if set to zero value

---

auth0/provider.go
auth0/resource_auth0_role.go
auth0/resource_auth0_role_test.go
auth0/resource_auth0_user.go
auth0/resource_auth0_user_test.go
auth0/resource_data.go
auth0/resource_data_test.go
example/email_template/main.tf
example/role/main.tf
example/user/main.tf

Fixes #141
* resource/auth0_role: `user_ids` is removed. In its place the following is introduced.
* resource/auth0_user: `roles` is added.
This change introduces some backwards incompatible changes as `auth0_role` no longer has a `user_ids` field. Instead `auth0_user.roles` should be used.

Fix role and permission handling

---

auth0/resource_auth0_client.go
auth0/resource_auth0_client_test.go

Fixes #152 
* resource/auth0_client: support rotating `client_secret` by changing the value of `client_secret_rotation_trigger`.
How it works, given a client resource as the following:
```
resource "auth0_client" "my_client" {
name = "Application - Acceptance Test - Rotate Secret"
}
```
if we change the value of `client_secret_rotation_trigger` it will trigger the `client_secret` …

Add support for client secret rotation

---

auth0/resource_auth0_client_grant.go
auth0/resource_auth0_client_grant_test.go

Fixes #159
* Check if scope was defined. If not, create an empty slice instead of leaving null.
* Add test to verify:
* Creating a `auth0_client_grant` with no scopes (`scope = [ ]`).
* Updating to add a scope (`scope = [ "create:foo" ]`).
* Updating again to remove any scopes (`scope = [  ]`).

Fix null scope issue

---

README.md
auth0/resource_auth0_user.go
auth0/resource_auth0_user_test.go
example/user/main.tf
website/docs/r/user.html.md

Adds the optional user profile attributes `name`, `family_name`, `given_name`, `blocked` and `picture`, which may be useful to set during user resource creation/modification. 
Available user profile attributes are detailed here: https://auth0.com/docs/users/references/user-profile-structure#user-profile-attributes

Add additional optional user profile attributes

---

auth0/resource_auth0_tenant.go
auth0/resource_auth0_tenant_test.go
example/tenant/main.tf

Adds the `enabled_locales` property to the tenant settings. This allows users to set the supported languages for the Universal Login - see https://auth0.com/docs/universal-login/i18n#setting-the-tenant-supported-languages.

Add enabled_locales property to tenant settings

---

auth0/provider.go
auth0/resource_auth0_global_client.go
auth0/resource_auth0_global_client_test.go
example/global_client/main.tf

* Adds ability to enable and manage html of Universal Custom Login page
```
$ make testacc TESTS=TestAccTenant
?   	github.com/terraform-providers/terraform-provider-auth0	[no test files]
=== RUN   TestAccTenant
--- PASS: TestAccTenant (1.76s)
PASS
coverage: 15.2% of statements
ok  	github.com/terraform-providers/terraform-provider-auth0/auth0	1.989s	coverage: 15.2% of statements
PASS
ok  	github.com/terraform-providers/terraform-provider-auth0/auth0/internal/random	0.186s	coverage: 0.0% of statements [no tests to run]
PASS
ok  	github.com/terraform-providers/terraform-provider-auth0/auth0/internal/validatio …
```

add "auth0_global_client" resource

---

CHANGELOG.md
auth0/resource_auth0_connection.go
auth0/structure_auth0_tenant.go

Fixes #181 
* Fix `flattenXXX` methods for tenant, handling `nil` values correctly.
```
$ make testacc TESTS=TestAccTenant                                       [11:29:28]
=== RUN   TestAccTenant
--- PASS: …
```

Fix tenant flatteners causing nil pointer dereference

---

auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go

* Extended `connection` resource in order to support GitHub Connection
```
$ make testacc TESTS=TestAccConnectionGitHub
?   	github.com/terraform-providers/terraform-provider-auth0	[no test files]
=== RUN   TestAccConnectionGitHub
--- PASS: TestAccConnectionGitHub (5.66s)
PASS
coverage: 10.8% …
```

added support for github connection

---

auth0/structure_auth0_connection.go

Fixes #191
There was a missed switch case to expand the connection in case of an `email` strategy.
Because of that, the connection would be created badly and without the totp and email template configurations.
```
$ make testacc TESTS=TestAccConnectionEmail
=== RUN   TestAccConnectionEmail
--- PASS: TestAccConnectionEmail (8.45s)
...
```

Paswordless connection creation bug

---

.github/release.yml
.travis.yml
CHANGELOG.md
GNUmakefile
auth0/internal/debug/debug.go
auth0/provider.go
auth0/resource_auth0_client.go
auth0/resource_auth0_client_test.go
go.mod
go.sum
vendor/golang.org/x/oauth2/README.md
vendor/golang.org/x/oauth2/transport.go
vendor/gopkg.in/auth0.v4/go.mod
vendor/gopkg.in/auth0.v4/go.sum
vendor/gopkg.in/auth0.v4/internal/client/client.go
vendor/gopkg.in/auth0.v4/management/client.go
vendor/gopkg.in/auth0.v4/meta.go
vendor/gopkg.in/auth0.v4/release
vendor/modules.txt

Fixes #196 
- Upgrade `go-auth0/auth0` which defines Scopes as a `map[string]interface{}` instead of an `interface{}`.
The issue is demonstrated by the example below. Notice how only the first instance of `S` ignores `V` during marshal.
```go
type S struct {
V interface{} `json:"v,omitempty"`
}
for _, s := range []S{
{V: nil},
{V: (map[string]interface{})(nil)},
{V: …
```

Fix for empty auth0_client.jwt_configuration.scope 

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go

Fixes #200 
* When reading back a connection, the `options` `configuration` field is not read back from the API response (which is encrypted) but is read from the state instead.

resource/auth0_connection: round-trip configuration values and avoid suppressing diffs

---

auth0/resource_auth0_hook.go
auth0/resource_auth0_hook_test.go

Fixes #209
* `resource/auth0_hook`: avoid sending `trigger_id` on updates.
* `resource/auth0_hook`: add update tests.
```
$ make testacc TESTS=TestAccHook                                         [10:49:29]
=== RUN …
```

fix trigger_id from being sent in update payload

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go

Adds the `team_id` and `key_id` options for `Apple` connections.
The `apple` strategy has been introduced in terraform-providers/terraform-provider-auth0#6.
* Add `team_id` option for `auth0_connection` resources
* Add `key_id` option for `auth0_connection` resources
* Add acceptance test for `Apple` connection
```
$ make testacc …
```

Add Apple connection options

---

auth0/resource_auth0_tenant.go

This is a tiny, trivial change. I didn't understand why the wrapping was needed either and as far as I can tell locally, it's not. Let's see if CI thinks differently 😉

resource_auth0_tenant: remove TODO

---

auth0/resource_auth0_client.go
auth0/resource_auth0_client_grant.go
auth0/resource_auth0_client_grant_test.go
auth0/resource_auth0_global_client.go
auth0/resource_auth0_global_client_test.go
auth0/resource_auth0_user.go
auth0/resource_auth0_user_test.go
auth0/resource_data.go
auth0/structure_auth0_connection.go

This PR changes something fairly fundamental to how this provider works. So far, testing whether a field has been defined in the terraform config, would be done using `GetOkExists`. This has been marked as deprecated by HashiCorp, but seemingly it remains for use for Boolean types.
* `resource_data`: Change utility functions `String`, `Int`, `Map`, `Slice`, `List`, `Set` and `JSON` to rely on `d.GetOk(key)` to check whether a key has been set. Note: the `Bool` function still relies on `d.GetOkExists(key)`.
* `resource/auth0_connection`: option conditions expand unconditionally instead of if `IsNewResource()` or `HasChange()`.
Fixes #237
Fixes #186 
Fixes #239 
```
$ make testacc
? …
```

Change String, Int, Map, Slice, List and Set to use GetOk instead of GetOkExists

---

auth0/resource_auth0_rule_config.go
auth0/resource_auth0_rule_config_test.go

* Set `ForceNew: true` for `auth0_rule_config.key`.
* Add more tests to verify the correct behavior.
Fixes #214 
```
$ make testacc TESTS=TestAccRuleConfig                   [14:21:01]
=== RUN   TestAccRuleConfig
--- PASS: TestAccRuleConfig (2.28s)
PASS
coverage: 7.2% of statements
ok      github.com/terraform-providers/terraform-provider-auth0/auth0   2.596s  coverage: 7.2% of statements
```
* Please do not …

Force new resource when auth0_rule_config.key has change

---

website/docs/r/tenant.html.md

* Add note to docs about not being able to create/destroy auth0_tenant resource (Auth0 API restriction)
* Add note to docs about not being able to add/remove extensions via TF (Auth0 API restriction)
It was by chance that I came across this thread while researching a project to implement Auth0 with multiple tenants.
https://community.auth0.com/t/management-api-to-create-a-tenant-and-to-install-and-configure-an-extension/40537
I think it would be really nice to have this information more prominent. I need to create multiple tenants and potentially install some extensions. I was expecting to do all of that with the auth0_tenant resource because typically TF can create and destroy most all resource types. I think not being able to create/destroy the resource is an exception to the norm, and …

Add notes to clarify tenant functionality

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go
docs/resources/connection.md
go.mod

Fixes #266
```
$ make testacc TESTS=TestAccConnectionOAuth2
=== RUN   TestAccConnectionOAuth2
--- PASS: TestAccConnectionOAuth2 (2.87s)
PASS
coverage: 12.5% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     3.258s  coverage: 12.5% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug     [no test files]
PASS
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/random    0.333s                                                                                                     coverage: 0.0% of statements [no tests to run] …
```

Added support for oauth2 config

---

README.md

Thanks again for your hard work on this Terraform provider, as a token of appreciation we decided to sponsor this project! This pull request adds the sponsorship message to the readme as agreed upon.
Keep up the good work!

Add Auth0 sponsorship message to the readme

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go

* Correctly sending username validation to Auth0
Fixes #238
```
make testacc TESTS=TestAccConnection
?   	github.com/terraform-providers/terraform-provider-auth0	[no test files]
=== RUN   TestAccConnection
--- PASS: TestAccConnection (2.01s)
=== RUN   TestAccConnectionAD
--- PASS: TestAccConnectionAD (0.85s)
=== RUN   TestAccConnectionAzureAD
--- PASS: TestAccConnectionAzureAD (7.16s)
=== RUN   TestAccConnectionOIDC
--- PASS: TestAccConnectionOIDC (1.80s)
=== RUN   TestAccConnectionWithEnbledClients
--- PASS: TestAccConnectionWithEnbledClients (19.63s)
=== RUN   TestAccConnectionSMS
--- PASS: TestAccConnectionSMS (0.90s)
=== RUN   TestAccConnectionEmail
--- PASS: TestAccConnectionEmail (6.55s)
=== RUN   TestAccConnectionSalesforce …
```

correctly transfer username validation to auth0

---

auth0/resource_auth0_client.go
example/connection/main.tf

* Fix handling of `mobile.android.sha256_cert_fingerprints` to be a slice of strings
* Fix incorrect handling of `mobile.ios.team_id`
* Fix incorrect handling of `mobile.ios.app_bundle_identifier`
Fixes #253 
```
$ make testacc TESTS=TestAccClient                                                                                                       [16:44:23]
go: downloading gopkg.in/auth0.v5 v5.3.0
--- PASS: TestAccClientGrant (4.65s)
--- PASS: TestAccClient (0.86s)
--- PASS: TestAccClientZeroValueCheck (2.12s)
--- PASS: …
```

Fix client mobile

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go
docs/resources/connection.md

* Adds set_user_root_attributes to more connections
* Depends on https://github.com/go-auth0/auth0/pull/192
```
...
```

Adds set_user_root_attributes to connections

---

auth0/resource_auth0_hook.go
auth0/resource_auth0_hook_test.go

* Add support for "HookSecrets" based on feedback from #205 
Fixes #205
```
$ make testacc TESTS=TestAccHookSecrets
=== RUN   TestAccHookSecrets
--- PASS: TestAccHookSecrets (8.46s)
PASS
coverage: 11.5% of statements
ok      github.com/terraform-providers/terraform-provider-auth0/auth0   9.361s  coverage: 11.5% of statements
?       github.com/terraform-providers/terraform-provider-auth0/auth0/internal/debug    [no test files]
PASS
ok      github.com/terraform-providers/terraform-provider-auth0/auth0/internal/random   0.492s  coverage: 0.0% of statements [no tests to run]
testing: warning: …
```

Add "HookSecrets" support through "auth0_hook"

---

docs/resources/connection.md

* For Google OAuth, docs specified Facebook client ID and secret instead of Google

Fix typo in connection docs

---

auth0/resource_auth0_log_stream.go
auth0/resource_auth0_log_stream_test.go

* Add support for the [SumoLogic log stream](https://auth0.com/docs/logs/streams/stream-logs-to-sumo-logic) type
* I did not update the docs as there is still an open issue for that: #306 
```
$ make testacc TESTS=TestAccLogStreamSumo
=== RUN   TestAccLogStreamSumo
--- PASS: TestAccLogStreamSumo (2.33s)
PASS
coverage: 8.8% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	2.806s	coverage: 8.8% of statements
?   	github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug	[no test files]
PASS
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/random	0.382s …
```

Support the Sumo Logic log stream type

---

docs/resources/client.md

* Modify `auth0_client` resource's doc
Fixes #332

Indicate needed scope to get client secrets in doc

---

auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go
docs/resources/connection.md

Fixes #320
This hooks up the `windowslive` social connection that was commented out. 
I've tested it against my Auth0 tenant, and it seems to correctly provision and configure a Windows Live connection – i.e. "Try Connection" works after applying the plan shown below. However, I was kind of guessing my way through this, so any feedback would be welcome.
```
+ resource "auth0_connection" "windowslive" {
+ enabled_clients      = [
+ "……",
+ "……",
]
+ id                   = (known after apply)
+ is_domain_connection = (known after apply)
+ name                 = "windowslive"
+ realms               = (known after apply)
+ strategy             = "windowslive"
+ strategy_version     = (known after apply)
+ options {
+ client_id                = "73831016-83b9-4215-a7a5-5be48677e743"
+ …
```

Hook up 'windowslive' social connection type

---

auth0/resource_auth0_tenant.go
docs/resources/tenant.md

* Add `enabled_locales` to Terraform documentation
* Moved `default_redirection_uri` to bottom of argument list, to match the source
* Changed to `TypeList` from `TypeSet` in `resource_auth0_tenant.go` as the order of arguments matter. The first locale in the list will be set as the default one. 

Minor fix to tenant config and documentation

---

auth0/resource_auth0_tenant.go

My test harness didn't capture the Type change. 
While #345 is right in that it is technically setup in Auth0, it only matters to the first object in the list. 
Reverting change.

Revert Type schema change

---

auth0/resource_auth0_prompt.go
auth0/resource_auth0_prompt_test.go

Pending https://github.com/go-auth0/auth0/pull/187 (will add test output and update here when that is merged/released)
Adds the new identifier_first argument to prompts. I will update the terraform provider as well once this lands and is tagged.
https://support.auth0.com/notifications/5fff0ab3f28427000a77941e
```
...
```

Add new identifier_first field to prompt

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go

* Add `display_name` to `auth0_connection` resource.
Fixes #288
```
$ make testacc TESTS=TestAccConnectionSAML                                                                                                         [18:52:07]
=== RUN   TestAccConnectionSAML
--- PASS: TestAccConnectionSAML (2.08s)
PASS
coverage: 10.6% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     2.377s  coverage: 10.6% of statements
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers …

Fix connection display name

---

auth0/resource_auth0_connection_test.go
auth0/resource_auth0_prompt_test.go

* Fix `auth0/resource_auth0_connection_test.go` to also set a `display_name` for OIDC (fixes change made by #304) 
* Fix `auth0/resource_auth0_prompt_test.go` to send a `identifier_first` upon initial prompt changes. Upstream made a change where setting `universal_login_experience` to `classic` would set `identifier_first` to false. This was an assumption in the test and the test now sends `identifier_first` along side `universal_login_experience`. 
```
make testacc                                                              
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_debugDefaults
--- PASS: TestProvider_debugDefaults (0.00s)
=== …
```

Fix Connection & Prompt tests 

---

auth0/resource_auth0_client.go

* Removes a legacy, information-only field `custom_login_page_preview`.
Fixes #360
```
kpurdon@syndio: ~/.../kpurdon/terraform-provider-auth0 make testacc TESTS=TestAccClient
--- PASS: TestAccClientGrant (23.79s)
--- PASS: TestAccClient (2.65s)
--- PASS: TestAccClientZeroValueCheck (5.78s)
--- PASS: TestAccClientRotateSecret (4.26s)
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (3.88s)
=== RUN   TestAccClientMobile
--- PASS: …
```

Remove auth0_client.custom_login_page_preview

---

go.mod
go.sum

Simple PR representing a version bump of the go auth0 version from v5.15 to v5.17

feat: Upgrade go auth0 version v5.15 to v5.17

---

docs/resources/client.md

The client argument `custom_login_page_preview` got removed in #379 but it is still available in the documentation.
_N/A_

Remove deprecated client argument from documentation

---

docs/resources/email_template.md

* Updates docs to match the `auth0_email_template.result_url` schema which should be optional based on https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_email_template.go#L50.
```
...
```

(docs): Fixed documentation of Optional argument.

---

docs/resources/guardian.md

Found some typos in the documentation for Auth0 guardian that I have introduced myself. This PR fixes the typos I found.

Updated some typos in docs

---

CHANGELOG.md
auth0/internal/hash/hash.go
auth0/internal/hash/hash_test.go
auth0/provider.go
auth0/resource_auth0_email_template_test.go
auth0/resource_auth0_organization.go
auth0/resource_auth0_organization_test.go
auth0/resource_auth0_role.go
auth0/resource_auth0_rule_test.go
auth0/resource_auth0_user.go
auth0/resource_data.go
auth0/structure_auth0_connection.go
docs/resources/organization.md
go.mod
go.sum

* Add `auth0_organization` resource. 
See: [Organizations](https://auth0.com/docs/api/management/v2#!/Organizations/post_organizations)
Fixes #454
```
$ make testacc TESTS=TestAccOrganization                                                                                                                                                                                            
=== RUN   TestAccOrganization
--- PASS: TestAccOrganization (2.15s)
PASS
coverage: 7.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     2.672s  coverage: 7.0% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug      [no …
```

Add auth0 organizations

---

auth0/resource_auth0_email_template.go
docs/resources/email_template.md

Adds the `'user_invitation'` email template option. 
See: https://auth0.com/docs/api/management/v2#!/Email_Templates/get_email_templates_by_templateName
```
...
```

Add the "user_invitation" email template option

---

auth0/resource_auth0_client.go
auth0/resource_auth0_client_test.go
docs/resources/client.md

* add allowed_clients attribute
Fixes #441
```
$ make testacc TESTS=TestAccClient
--- PASS: TestAccClientGrant (8.52s)
--- PASS: TestAccClient (1.99s)
--- PASS: TestAccClientZeroValueCheck (4.62s)
--- PASS: TestAccClientRotateSecret (3.38s)
--- PASS: TestAccClientInitiateLoginUri (0.06s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (3.05s)
=== RUN   TestAccClientMobile
--- PASS: TestAccClientMobile (3.37s)
=== RUN   TestAccClientMobileValidationError
--- PASS: …
```

Add support for allowed_clients 

---

CHANGELOG.md
auth0/resource_auth0_action.go
example/action/main.tf

* Update `auth0_action` deployment to check for `built` status.
Fixes #470 
```
$ make testacc TESTS=TestAccAction
=== RUN   TestAccAction
--- PASS: TestAccAction (4.80s)
PASS
coverage: 7.9% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     5.402s  coverage: 7.9% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/digitalocean       [no test files]
PASS
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/hash       0.250s …
```

Fix action deployment

---

auth0/resource_auth0_action.go
example/action/main.tf

* Treat `auth0_action` `secrets` as a `List` instead of a `Set`. This should solve the issue with secrets not being sent to the Management API
* Add an example action
Fixes #477
```
...
```

Fix action secrets (attempt #2 🙈)

---

auth0/resource_auth0_connection.go
auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go
docs/resources/connection.md

* Extend existing auth0_connection resource to support custom Entity ID in samlp connection options
```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_debugDefaults
--- PASS: TestProvider_debugDefaults (0.00s)
=== RUN   TestAccBranding
--- PASS: TestAccBranding (5.07s)
--- PASS: TestAccClientGrant (26.83s)
--- PASS: TestAccClient (2.73s)
--- PASS: TestAccClientZeroValueCheck (5.70s)
--- PASS: TestAccClientRotateSecret (3.92s)
--- PASS: …
```

Support entity_id in samlp connection

---

.github/labeler.yml
CHANGELOG.md
auth0/provider.go
auth0/resource_auth0_trigger_binding.go
auth0/resource_auth0_trigger_binding_test.go
docs/resources/trigger_binding.md

* Introduce `auth0_trigger_binding` resource (a.k.a. action flow)
Fixes #480 
<details>
<summary>Click to expand test output</summary>
```
$ make testacc TESTS=TestAccTriggerBinding
=== RUN   TestAccTriggerBinding
--- PASS: TestAccTriggerBinding (5.16s)
PASS
coverage: 8.8% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     5.479s  coverage: 8.8% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/digitalocean       [no test files]
PASS
ok …
```

Add `auth0_trigger_binding`

---

CHANGELOG.md
auth0/resource_auth0_client.go
auth0/resource_auth0_client_test.go
docs/resources/client.md
scripts/gendocs.go

This setting is used to toggle "Enable native Apple/Facebook" login on
and off.
* Adds support for the `native_social_login` stanza in the Client API. 
* Adds documentation
* Updates Mobile Tests
Fixes #0000
Ran the whole suite, but only included the relevant part:
```
$ make testacc TESTS=TestAccClient          
--- PASS: TestAccClientGrant (22.16s)
--- PASS: TestAccClient (2.16s)
--- PASS: TestAccClientZeroValueCheck (11.15s)
--- PASS: TestAccClientRotateSecret (3.07s)
--- PASS: …
```

Implements the native_social_login stanza on the Client API.

---

.github/labeler.yml
CHANGELOG.md
auth0/provider.go
auth0/resource_auth0_prompt_custom_text.go
auth0/resource_auth0_prompt_custom_text_test.go
docs/resources/prompt_custom_text.md

* Introduces `auth0_prompt_custom_text`
<details>
<summary>Click to expand test output</summary>
```
$ make testacc TESTS=TestAccPromptCustomText
=== RUN   TestAccPromptCustomText
--- PASS: TestAccPromptCustomText (4.68s)
PASS
coverage: 5.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     7.574s  coverage: 5.0% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/digitalocean       [no test files]
PASS
ok …
```

Added auth0 prompt custom text

---

auth0/resource_auth0_guardian.go
auth0/resource_auth0_guardian_test.go
docs/resources/guardian.md
example/guardian/main.tf

* Adds the `email` mfa factor
<details><summary>Click to expand</summary>
<p>
```
$ make testacc TESTS=TestAccGuardian
=== RUN   TestAccGuardian
--- PASS: TestAccGuardian (93.45s)
PASS
coverage: 11.6% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     93.861s coverage: 11.6% of statements
?       github.com/alexkappa/terraform-provider-auth0/auth0/internal/digitalocean       [no test files]
PASS
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/hash …
```

add email mfa factor

---

auth0/resource_auth0_log_stream.go
auth0/resource_auth0_log_stream_test.go
docs/resources/log_stream.md
example/log_stream/main.tf

* Add support for JSONOBJECT form for http log stream. This feature is supported in the UI and should be in terraform provider.

feat(log_stream): support JSONOBJECT format

---

docs/resources/role.md

role_id looks to have been removed with this pull request https://github.com/alexkappa/terraform-provider-auth0/pull/202 but still appears in the documentation. This is misleading and can take trial and error, searching the code, or searching the github repo PRs/issues to determine that it is removed.

Remove role_id from role documentation

---

auth0/resource_auth0_log_stream_test.go

Fixes error in test logic introduced with https://github.com/alexkappa/terraform-provider-auth0/pull/445. 
```
=== RUN   TestAccLogStreamHTTP
--- PASS: TestAccLogStreamHTTP (5.19s)
PASS
Process finished with the exit code 0
```

Fix log stream tests

---

auth0/resource_auth0_connection_test.go
auth0/structure_auth0_connection.go

* Add support for google-apps connection strategy options
```
$ make testacc TESTS=TestAccConnectionGoogleApps
=== RUN   TestAccConnectionGoogleApps
--- PASS: TestAccConnectionGoogleApps (2.15s)
PASS
coverage: 9.1% of statements
ok  	github.com/alexkappa/terraform-provider-auth0/auth0	2.394s	coverage: 9.1% of statements
?   	github.com/alexkappa/terraform-provider-auth0/auth0/internal/debug	[no test files]
PASS
ok  	github.com/alexkappa/terraform-provider-auth0/auth0/internal/random	0.171s	coverage: 0.0% of statements [no tests to run]
PASS …
```

Add support for google-apps connection strategy options

---

auth0/data_source_auth0_client.go
auth0/data_source_auth0_client_test.go
auth0/provider.go
auth0/resource_data_test.go
docs/datasources/client.md

Reintroducing the client data source that was originally introduced by #363 by @yinzara. This PR however, it more focused in that it _only_ pertains to the client data source. This PR can serve as a template for future data source contributions.
I've identified a couple points of interest below, mostly around the exclusion of certain properties and the testing inefficiencies.
```
=== RUN   TestAccDataClientById
--- PASS: TestAccDataClientById (4.30s)
=== RUN   TestAccDataClientByName
--- PASS: TestAccDataClientByName (4.87s)
...
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers …

DXCDT-20: Client data source

---

auth0/provider.go
auth0/provider_test.go
docs/index.md

* add support for [Management API tokens](https://auth0.com/docs/security/tokens/access-tokens/management-api-access-tokens) for authenticating to auth0
I ran the acceptance tests using `AUTH0_MANAGEMENT_TOKENS` tokens so I'm not sure if the test failures are flaky tests, problems with using a management token, or expected behavior.
<details>
<summary>output</summary>
```
=== RUN   TestAccAction
--- PASS: TestAccAction (5.20s)
=== RUN   TestAccBranding
--- PASS: TestAccBranding (10.02s)
--- PASS: TestAccClientGrant (27.15s)
--- PASS: TestAccClient (1.64s)
--- PASS: TestAccClientZeroValueCheck (10.03s) …
```

add support for Management API tokens
