auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go
Support already exists in the Go client - just adding it to the provider
=> Add support for Allowed Logout URLs

.goreleaser.yml, Gopkg.lock, vendor/github.com/yieldr/go-auth0/management/client.go, vendor/github.com/yieldr/go-auth0/management/management.go, wercker.yml
Added `goreleaser` to the build/release pipeline to simplify releasing. There's already a PR helping with this (#2) but I find this approach more straightforward.
Let me know what you think.
=> [Feature] Release binaries using goreleaser

auth0/resource_auth0_resource_server.go, auth0/resource_auth0_rule.go, auth0/resource_auth0_rule_config.go, auth0/resource_auth0_rule_config_test.go
Check remote server from [the list](#7 )
=> Resource Server read remote values correctly

auth0/resource_auth0_client.go, auth0/resource_auth0_client_grant_test.go, auth0/resource_auth0_client_test.go
Would you mind taking a look at this and let me know if you see any problems?
I'm something of a Go novice, so any pointers would be welcome
=> Implement schema builder for reading resources

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go
Ref: https://github.com/yieldr/go-auth0/pull/13
=> Add requires_username property to Auth0 connection

Gopkg.lock, Gopkg.toml, auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go, auth0/util.go, example/client/main.tf, vendor/github.com/yieldr/go-auth0/management/connection.go, vendor/github.com/yieldr/go-auth0/management/management.go, vendor/github.com/yieldr/go-auth0/management/user.go, vendor/github.com/yieldr/go-auth0/management/utils.go
=> Jeff french improve addons

example/tenant/main.tf, website/docs/index.html.markdown, website/docs/r/tenant.html.markdown
=> docs: auth0_tenant and website index

auth0/resource_auth0_connection.go
This adds the adfs_server option for Auth0 connections.
=> feat(connection): Add adfs_server option

README.md
* Update supported Auth0 resources to include Users in README.md
=> Update supported Auth0 resources to include Users

example/connection/main.tf
* Fix example connection manifest. Currently it's incorrect
=> fix: connection example was incorrect

auth0/resource_auth0_user.go
* Fixes user's `user_metadata` and `app_metadata` not being properly set
* Makes user's `password` field sensitive
=> Fix resource auth0_user bugs in user_metadata and app_metadata and password

README.md, auth0/resource_auth0_tenant.go, auth0/resource_auth0_tenant_test.go
* Add `flags` to `tenant`
* Add `universal_login` to `tenant`
* Add `idle_session_lifetime` to `tenant`
=> Add flags, universal_login and idle_session_lifetime to tenant

CHANGELOG.md, README.md
Switches the github owner from yieldr to alexkappa in the documentation.
=> Update github owner yieldr->alexkappa

CHANGELOG.md, auth0/resource_auth0_tenant.go, auth0/resource_auth0_tenant_test.go, auth0/structure_auth0_tenant.go, go.mod, go.sum, vendor/gopkg.in/auth0.v4/CHANGELOG.md, vendor/gopkg.in/auth0.v4/management/management.gen.go, vendor/gopkg.in/auth0.v4/management/tenant.go, vendor/modules.txt
Fixes #167
* `auth0_tenant`: add `use_scope_descriptions_for_consent` flag
```
$ make testacc TESTS=TestAccTenant
=== RUN   TestAccTenant
--- PASS: TestAccTenant (3.23s)
PASS
```
=> update dep and define scope descriptions on tenant

auth0/resource_auth0_role.go, version/version.go
Fixes #193
* `auth0_role`: remove `role_id` field.
```
$ make testacc TESTS=TestAccRole                                    [14:05:33]
=== RUN   TestAccRole
--- PASS: TestAccRole (4.75s)
PASS
coverage: 15.1% of …
```
=> Remove auth0_role.role_id

auth0/resource_auth0_role.go, auth0/resource_auth0_role_test.go
Fixes #188 
* Paginate role permissions to account for roles with many permissions (>50)
```
$ make testacc TESTS=TestAccRolePermissions                              [10:43:18]
=== RUN   TestAccRolePermissions
--- …
```
=> Paginate auth0_role.permissions

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, go.mod, go.sum, vendor/github.com/hashicorp/terraform-plugin-sdk/acctest/doc.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_config.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/set.go, vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go, vendor/github.com/hashicorp/terraform-plugin-sdk/terraform/state.go, vendor/github.com/hashicorp/terraform-plugin-test/helper.go, vendor/github.com/hashicorp/terraform-plugin-test/util.go, vendor/modules.txt
* Migrate `strategy_version` from a string to an int.
Fixes #234
=> Migrate schema for strategy_version

auth0/resource_auth0_client.go, auth0/resource_auth0_email.go, auth0/resource_auth0_global_client_test.go, auth0/resource_auth0_resource_server.go, auth0/resource_auth0_user.go, auth0/resource_auth0_user_test.go, auth0/resource_data.go, auth0/resource_data_test.go, auth0/structure_auth0_connection.go, auth0/structure_auth0_tenant.go
* Mark `name`, `nickname` and `picture` as computed values.
* Read `user_metadata` and `app_metadata` only if the resource is new or has changes.
* Rename internal `Data` interface to `ResourceData`.
* Define `ResourceData.GetOk(key string)` method.
Fixes #218 
```
$ make testacc TESTS=TestAccUserIssue218
=== RUN   TestAccUserIssue218
--- PASS: TestAccUserIssue218 (2.23s)
PASS
coverage: 13.5% of statements
ok      github.com/terraform-providers/terraform-provider-auth0/auth0   2.287s  coverage: 13.5% of statements
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and- …
=> Fix auth0_user issues with JSON

auth0/resource_auth0_hook.go
* Fix send-phone-message hook
```
...
```
=> Fix send-phone-message hook

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/workflows/codeql.yml, CHANGELOG.md, auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go, auth0/resource_data.go, auth0/resource_data_test.go
* Improve handling of `addons.samlp` to use camel cased attributes.
* Improve handling of `mobile.ios` and `mobile.android`.
* Add `Set` method to `ResourceData` which can set a `key` only if the `value` are not nil.
* Remove `Iterator.Range`.
Fixes #226
```
$ make testacc TESTS=TestAccClient
--- PASS: TestAccClientGrant (3.95s)
--- PASS: TestAccClient (0.92s)
--- PASS: TestAccClientZeroValueCheck (2.26s)
--- PASS: TestAccClientRotateSecret (1.59s)
--- PASS: TestAccClientInitiateLoginUri …
```
=> Fix client samlp add-on to use camel case fields instead of snake case

website/docs/index.html.md
Fixes https://github.com/terraform-providers/terraform-provider-auth0/issues/22
* Add a note about importing resources in the docs home page.
Fixes https://github.com/terraform-providers/terraform-provider-auth0/issues/22
=> Add a note about importing resources

auth0/provider.go, auth0/provider_test.go, auth0/resource_auth0_client.go, auth0/resource_auth0_client_grant.go, auth0/resource_auth0_client_test.go, auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, auth0/resource_auth0_custom_domain.go, auth0/resource_auth0_email.go, auth0/resource_auth0_email_template.go, auth0/resource_auth0_email_template_test.go, auth0/resource_auth0_global_client.go, auth0/resource_auth0_hook.go, auth0/resource_auth0_prompt.go, auth0/resource_auth0_resource_server.go, auth0/resource_auth0_resource_server_test.go, auth0/resource_auth0_role.go, auth0/resource_auth0_role_test.go, auth0/resource_auth0_rule.go, auth0/resource_auth0_rule_config.go, auth0/resource_auth0_tenant.go, auth0/resource_auth0_tenant_test.go, auth0/resource_auth0_user.go, auth0/resource_auth0_user_test.go, auth0/resource_data.go, auth0/structure_auth0_connection.go, auth0/structure_auth0_tenant.go, go.mod, go.sum
* Upgrades the `go-auth0/auth0` package to v5 unlocking new features (log streams, fixed saml connection, ...)
```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_debugDefaults
--- PASS: TestProvider_debugDefaults (0.00s)
--- PASS: TestAccClientGrant (25.54s)
--- PASS: TestAccClient (1.55s)
--- PASS: TestAccClientZeroValueCheck (10.02s)
--- PASS: TestAccClientRotateSecret (3.02s)
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: …
```
=> Upgrade go-auth0/auth0 from v4 -> v5

.github/labeler.yml, .github/workflows/labeler.yml, auth0/resource_auth0_client.go
Update labeler action to v3 and use a personal access token to allow all contributors to use the action.
=> update to v3 and add resources

auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go, docs/resources/client.md
* add support for client refresh_token fields 
```
idle_token_lifetime
infinite_idle_token_lifetime
infinite_token_lifetime 
```
Fixes #311 
Fixes #307
```
$ make testacc TESTS=TestAccClient    
--- PASS: TestAccClientGrant (25.72s)
--- PASS: TestAccClient (2.79s)
--- PASS: TestAccClientZeroValueCheck (5.65s)
--- PASS: TestAccClientRotateSecret (4.21s)
--- PASS: TestAccClientInitiateLoginUri (0.03s)
=== RUN   TestAccClientJwtScopes
--- PASS: TestAccClientJwtScopes (3.81s)
=== RUN …
```
=> add additional refresh token config options

auth0/resource_auth0_email_template.go, docs/resources/email_template.md
Just adding the email template `verify_email_by_code`
=> Add verify_email_by_code template

.github/workflows/sweep.yml
* Add steps to successfully run `make sweep`. 
=> Add necessary build steps to actually run Github Action 'sweep'

docs/resources/connection.md
Ran into `unexpected block` Terraform errors when attempting to configure a SAML connection using the provider -- turns out the documentation had some typos :)
* `idpinitiated` should be `idp_initiated`.
* `client_authorizequery` should be `client_authorize_query`.
=> Documentation Update: Update typo in SAML connection options documentation.

docs/resources/branding.md
* Add font coloring to branding docs page
n/a
=> Update branding.md - code coloring

docs/resources/prompt.md, example/prompt/main.tf
Reasoning for docs update: Functionality for the `identifier_first` argument is supported in the provider but is not present in the documentation. 
N/A
=> Update docs for auth0_prompt

docs/resources/client_grant.md
=> Add Import Documentation for client_grants

docs/resources/log_stream.md
* add the `import` documentation for `auth0_log_stream` resource
* correct the `auth0_log_stream` resource name
=> docs: update auth0 log stream resource documentation

docs/resources/role.md
Renaming role_id to id as it seems to be a typo in the docs. 
Fixes #423 
=> #423 Fix role docs

docs/resources/connection.md
- Resolves error applying samlp connection configuration 
```
...
```
@alexkappa
=> Fixed typo binding_method -> protocol_binding

CHANGELOG.md
* Change 1
* Change 2
Fixes #0000
```
...
```
=> Add changelog for 0.26.2

docs/resources/user.md
* Update verbiage to make password requirement more clear
n/a
=> Make clear that passwords are required when not using SMS

auth0/resource_auth0_guardian.go, auth0/resource_auth0_guardian_test.go, docs/resources/guardian.md
* added OTP option to Guardian
Fixes #0000
```
make testacc TESTS=TestAccGuardian
terraform-provider-auth0_custom-domain_1 is up-to-date
=== RUN   TestAccGuardian
--- PASS: TestAccGuardian (109.81s)
PASS
coverage: 12.0% of statements
ok      github.com/alexkappa/terraform-provider-auth0/auth0     110.601s        coverage: 12.0% of statements
PASS
ok      github.com/alexkappa/terraform-provider-auth0/auth0/internal/hash       0.469s  coverage: 0.0% of statements [no tests to run]
testing: warning: no …
```
=> Add otp to auth0 guardian
